# Generated by Django 3.1.2 on 2020-10-27 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('ubigeo', '0001_initial'),
        ('default', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docid', models.CharField(max_length=20)),
                ('typedoc', models.CharField(choices=[('D', 'DNI'), ('P', 'PASAPORTE')], max_length=1)),
                ('last_name0', models.CharField(max_length=150)),
                ('last_name1', models.CharField(max_length=150)),
                ('first_name', models.CharField(max_length=150)),
                ('birthday', models.DateField(null=True)),
                ('sex', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('civil', models.CharField(choices=[('S', 'Soltero'), ('C', 'Casado'), ('V', 'Viudo'), ('D', 'Divorciado'), ('O', 'Otros')], max_length=2)),
                ('mail', models.CharField(max_length=100, null=True)),
                ('cellphone', models.CharField(max_length=9, null=True)),
                ('address', models.CharField(blank=True, max_length=150, null=True)),
                ('user_create', models.CharField(max_length=15)),
                ('user_update', models.CharField(blank=True, max_length=15, null=True)),
                ('date_create', models.DateField(auto_now_add=True)),
                ('date_update', models.DateField(auto_now=True, null=True)),
                ('eid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='default.entity')),
                ('r_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ubigeo.department')),
                ('r_district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ubigeo.district')),
                ('r_province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ubigeo.province')),
            ],
            options={
                'unique_together': {('eid', 'docid')},
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(db_index=True, max_length=15, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('depid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='default.departments')),
                ('docid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.person')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario de sistema',
                'verbose_name_plural': 'Usuarios del sistema',
            },
        ),
    ]
