# Generated by Django 3.1.2 on 2020-12-18 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acl', '0002_modules_url_external'),
    ]

    operations = [
        migrations.AddField(
            model_name='modules',
            name='color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='modules',
            name='icon',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
