# Generated by Django 3.1.2 on 2020-12-20 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acl', '0003_auto_20201218_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='modules',
            name='type_module',
            field=models.CharField(blank=True, choices=[('DESARROLLADO', 'DESARROLLADO'), ('GESTIONADO', 'GESTIONADO')], max_length=20, null=True),
        ),
    ]
