# Generated by Django 3.1.2 on 2020-10-27 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('eid', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('legal_representative', models.CharField(max_length=250, null=True)),
                ('user_create', models.CharField(max_length=15)),
                ('user_update', models.CharField(blank=True, max_length=15, null=True)),
                ('date_create', models.DateField(auto_now_add=True)),
                ('date_update', models.DateField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Departments_type',
            fields=[
                ('tid', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('state', models.CharField(blank=True, max_length=2, null=True)),
                ('order', models.IntegerField()),
                ('user_create', models.CharField(max_length=15)),
                ('user_update', models.CharField(blank=True, max_length=15, null=True)),
                ('date_create', models.DateField(auto_now_add=True)),
                ('date_update', models.DateField(auto_now=True, null=True)),
                ('eid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='default.entity')),
            ],
            options={
                'unique_together': {('eid', 'tid')},
            },
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depid', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=250)),
                ('abbreviation', models.CharField(blank=True, max_length=20, null=True)),
                ('parent', models.CharField(blank=True, max_length=15, null=True)),
                ('state', models.CharField(blank=True, max_length=2, null=True)),
                ('order', models.IntegerField()),
                ('user_create', models.CharField(max_length=15)),
                ('user_update', models.CharField(blank=True, max_length=15, null=True)),
                ('date_create', models.DateField(auto_now_add=True)),
                ('date_update', models.DateField(auto_now=True, null=True)),
                ('eid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='default.entity')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='default.departments_type')),
            ],
            options={
                'unique_together': {('eid', 'depid')},
            },
        ),
    ]
