# Generated by Django 3.1.2 on 2020-11-11 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('default', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expedient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_person', models.CharField(choices=[('N', 'Natural'), ('J', 'Jurídica')], max_length=1)),
                ('j_ruc', models.CharField(blank=True, max_length=11, null=True)),
                ('j_business_name', models.CharField(blank=True, max_length=250, null=True)),
                ('j_address', models.CharField(blank=True, max_length=250, null=True)),
                ('n_person_id', models.CharField(max_length=50)),
                ('n_dni', models.CharField(max_length=8)),
                ('n_last_name0', models.CharField(max_length=80)),
                ('n_last_name1', models.CharField(max_length=80)),
                ('n_first_name', models.CharField(max_length=100)),
                ('n_cellphone', models.CharField(max_length=9)),
                ('n_email', models.CharField(max_length=100)),
                ('state', models.CharField(choices=[('SGD', 'Registrado en SGD'), ('OBS', 'Observado'), ('EMP', 'Enviado a Mesa de Partes')], max_length=3)),
                ('date_register', models.DateTimeField()),
                ('sgd_expedient', models.CharField(blank=True, max_length=50, null=True)),
                ('sgd_date_register', models.DateTimeField(blank=True, null=True)),
                ('user_create', models.CharField(max_length=15)),
                ('user_update', models.CharField(blank=True, max_length=15, null=True)),
                ('date_create', models.DateField(auto_now_add=True)),
                ('date_update', models.DateField(auto_now=True, null=True)),
                ('entity_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='default.entity')),
            ],
            options={
                'db_table': '"mpv"."expedient"',
            },
        ),
    ]
