# Generated by Django 3.1.2 on 2020-11-11 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expedient', '0002_typedocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50)),
                ('folio', models.CharField(max_length=3)),
                ('subject', models.TextField()),
                ('observation', models.TextField(blank=True, null=True)),
                ('type_documentation', models.CharField(choices=[('S', 'Subsanar'), ('P', 'Principal')], max_length=1)),
                ('user_create', models.CharField(max_length=15)),
                ('user_update', models.CharField(blank=True, max_length=15, null=True)),
                ('date_create', models.DateField(auto_now_add=True)),
                ('date_update', models.DateField(auto_now=True, null=True)),
                ('expedient_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='expedient.expedient')),
                ('type_document_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='expedient.typedocument')),
            ],
            options={
                'db_table': '"mpv"."document"',
            },
        ),
    ]
