# Generated by Django 3.1.2 on 2020-11-13 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expedient', '0004_auto_20201113_0534'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expedient',
            old_name='entity_id',
            new_name='entity',
        ),
    ]
