# Generated by Django 3.1.2 on 2020-11-13 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expedient', '0005_auto_20201113_0537'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='expedient_id',
            new_name='expedient',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='type_document_id',
            new_name='type_document',
        ),
    ]
