# Generated by Django 3.1.2 on 2020-11-19 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedient', '0006_auto_20201113_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='document_name',
            field=models.CharField(default=1, max_length=80),
            preserve_default=False,
        ),
    ]
