# Generated by Django 3.1.2 on 2020-11-20 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expedient', '0007_document_document_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='expedient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='expedient.expedient'),
        ),
        migrations.CreateModel(
            name='Attached',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('route', models.CharField(max_length=250)),
                ('type_attached', models.CharField(choices=[('P', 'Principal'), ('A', 'Anexo')], max_length=1)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='expedient.document')),
            ],
            options={
                'db_table': '"mpv"."attached"',
            },
        ),
    ]
