# Generated by Django 3.1.2 on 2020-11-23 06:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('expedient', '0008_auto_20201120_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='attached',
            name='date_create',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attached',
            name='date_update',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='attached',
            name='user_create',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attached',
            name='user_update',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
