# Generated by Django 3.1.2 on 2020-11-23 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedient', '0009_auto_20201123_0658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attached',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='attached',
            name='date_update',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
