# Generated by Django 3.1.2 on 2020-11-25 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expedient', '0012_auto_20201125_0627'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adjunct',
            fields=[
                ('adjunct_id', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('route', models.CharField(max_length=250)),
                ('user_create', models.CharField(max_length=15)),
                ('user_update', models.CharField(blank=True, max_length=15, null=True)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': '"mpv"."adjunct"',
            },
        ),
        migrations.RemoveField(
            model_name='document',
            name='id',
        ),
        migrations.AddField(
            model_name='document',
            name='attached_name',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='attached_route',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='document_id',
            field=models.CharField(default=1, max_length=200, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Attached',
        ),
        migrations.AddField(
            model_name='adjunct',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='expedient.document'),
        ),
    ]
