# Generated by Django 3.1.2 on 2020-11-26 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedient', '0013_auto_20201125_0641'),
    ]

    operations = [
        migrations.AddField(
            model_name='expedient',
            name='number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
