# Generated by Django 3.1.2 on 2020-11-26 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expedient', '0015_auto_20201126_0637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='expedient',
        ),
    ]
