# Generated by Django 3.1.2 on 2020-11-26 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expedient', '0016_remove_document_expedient'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='expedient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='expedient.expedient'),
            preserve_default=False,
        ),
    ]
