# Generated by Django 3.1.2 on 2021-01-04 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedient', '0017_document_expedient'),
    ]

    operations = [
        migrations.AddField(
            model_name='expedient',
            name='notified',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
